name: Deploy to Beta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  APP_NAME: DeploymentTest
  TARGET_HOST: ${{ secrets.TARGET_HOST_BETA }}
  TARGET_PORT: ${{ secrets.TARGET_PORT_BETA }}
  TARGET_USERNAME: ${{ secrets.USERNAME_BETA }}
  SERVICE_NAME: test-app
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 
    - run: dotnet publish ${{env.APP_NAME}} -o publish --configuration Release
    
    - name: Deploy
      uses: appleboy/scp-action@master
      env:
        HOST: ${{env.TARGET_HOST}}
        USERNAME: ${{env.TARGET_USERNAME}}
        PORT: ${{env.TARGET_PORT}}
        KEY: ${{ secrets.SSH_BETA }}
      with:
        source: "publish"
        target: "/var/www/${{env.APP_NAME}}"
        strip_components: 1
        
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{env.TARGET_HOST}}
        USERNAME: ${{env.TARGET_USERNAME}}
        PORT: ${{env.TARGET_PORT}}
        KEY: ${{ secrets.ssh_beta }}
        script: |
          systemctl restart ${{env.SERVICE_NAME}} &
