name: Deploy to Beta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  APP_NAME: DeploymentTest
  TARGET_HOST: srv07.mikr.us
  TARGET_PORT: 10224
  TARGET_USERNAME: root
  SERVICE_NAME: test-app
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' 
    - run: dotnet publish ${{env.APP_NAME}} -o publish --configuration Release
    
    - name: Deploy
      uses: appleboy/scp-action@master
      env:
        HOST: $TARGET_HOST
        USERNAME: $TARGET_USERNAME
        PORT: $TARGET_PORT
        KEY: ${{ secrets.ssh_beta }}
      with:
        source: "publish"
        target: "/var/www/$APP_NAME"
        strip_components: 1
        
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        HOST: $TARGET_HOST
        USERNAME: $TARGET_USERNAME
        PORT: $TARGET_PORT
        KEY: ${{ secrets.ssh_beta }}
        script: |
          systemctl restart $SERVICE_NAME &
